"""admin-ease: invites, settings, user expiry/quota/tags

Revision ID: 0002_admin_ease
Revises: 0001_baseline
Create Date: 2026-06-28 10:24:52.801494
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0002_admin_ease'
down_revision: Union[str, None] = '0001_baseline'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invite_codes',
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('role', sa.Enum('user', 'admin', 'owner', name='userrole'), nullable=False),
    sa.Column('max_uses', sa.Integer(), nullable=False),
    sa.Column('uses', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('code')
    )
    with op.batch_alter_table('invite_codes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invite_codes_active'), ['active'], unique=False)

    op.create_table('settings',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.String(length=2048), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('gpu_hours_limit', sa.Float(), nullable=True))
        # server_default so existing rows get an empty list when this NOT NULL
        # column is added to a populated users table.
        batch_op.add_column(sa.Column('tags', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False, server_default=sa.text("'[]'")))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('tags')
        batch_op.drop_column('gpu_hours_limit')
        batch_op.drop_column('expires_at')

    op.drop_table('settings')
    with op.batch_alter_table('invite_codes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invite_codes_active'))

    op.drop_table('invite_codes')
    # ### end Alembic commands ###
