#!/usr/bin/env bash
# Generate all SATYAMEBA secrets idempotently: .env, RSA JWT keypair, TLS certs.
# Safe to re-run — existing files are left untouched unless --force is given.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

FORCE=0
DOMAIN="satyameba.local"
for arg in "$@"; do
  case "$arg" in
    --force) FORCE=1 ;;
    --domain=*) DOMAIN="${arg#*=}" ;;
  esac
done

rand() { openssl rand -hex "${1:-24}"; }
mkdir -p secrets/certs

# ---- .env -----------------------------------------------------------------
if [[ -f .env && $FORCE -eq 0 ]]; then
  echo "[=] .env already exists (use --force to regenerate)"
else
  DB_PW="$(rand 16)"
  ADMIN_PW="$(rand 12)"
  HUB_TOKEN="$(rand 32)"
  INTERNAL="$(rand 32)"
  GRAFANA_PW="$(rand 12)"
  cat > .env <<EOF
# Generated by gen_secrets.sh on $(date -u +%FT%TZ)
SAT_ENVIRONMENT=production
SAT_PROJECT_NAME=SATYAMEBA
SAT_OWNER=Samaraho Mukherjee

POSTGRES_USER=satyameba
POSTGRES_PASSWORD=${DB_PW}
POSTGRES_DB=satyameba
SAT_DATABASE_URL=postgresql+psycopg2://satyameba:${DB_PW}@db:5432/satyameba

SAT_JWT_ALGORITHM=RS256
SAT_JWT_PRIVATE_KEY_PATH=/run/secrets/jwt_private.pem
SAT_JWT_PUBLIC_KEY_PATH=/run/secrets/jwt_public.pem
SAT_ACCESS_TOKEN_TTL_SECONDS=900
SAT_REFRESH_TOKEN_TTL_SECONDS=604800

SAT_REQUEST_SIGNING_ENABLED=true
SAT_REQUEST_SIGNING_SKEW_SECONDS=120

SAT_BOOTSTRAP_ADMIN_EMAIL=admin@${DOMAIN}
SAT_BOOTSTRAP_ADMIN_USERNAME=admin
SAT_BOOTSTRAP_ADMIN_PASSWORD=${ADMIN_PW}

SAT_HUB_API_URL=http://jupyterhub:8081/hub/api
SAT_HUB_API_TOKEN=${HUB_TOKEN}
SAT_HUB_PUBLIC_URL=/hub
SAT_INTERNAL_SHARED_SECRET=${INTERNAL}
SAT_SSO_TOKEN_TTL_SECONDS=60

SAT_PROMETHEUS_URL=http://prometheus:9090
SAT_REDIS_URL=redis://redis:6379/0

SAT_SPAWNER=docker
SAT_NOTEBOOK_IMAGE=satyameba/notebook:latest
SAT_NETWORK=satyameba_net
SAT_GPU_ENABLED=false
SAT_GPU_RESOURCE=gpu
SAT_MEM_LIMIT=4G
SAT_CPU_LIMIT=2

SAT_SHARED_VOLUME=satyameba-shared
SAT_SHARED_MODE=rw

SAT_USER_STORAGE_MODE=volume
SAT_USER_HOST_BASE=/srv/satyameba/users
SAT_SHARED_HOST_PATH=/srv/satyameba/shared

SAT_EXPECTED_USERS=8
SAT_USER_STORAGE_LIMIT_GB=20
SAT_STORAGE_QUOTA_ENFORCE=false
SAT_FREE_STORAGE_GB=0
SAT_TOTAL_STORAGE_GB=0

SAT_CORS_ORIGINS=https://${DOMAIN},https://localhost
SAT_RATE_LIMIT_PER_MINUTE=120
SAT_AUTH_RATE_LIMIT_PER_MINUTE=10
SAT_BOT_FILTER_ENABLED=true
SAT_REQUIRE_ADMIN_2FA=false
SAT_NODE_OFFLINE_SECONDS=90
SAT_AUDIT_RETENTION_DAYS=0
SAT_MAX_UPLOAD=0
SAT_SANDBOX_RUNTIME=

GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PW}
EOF
  chmod 600 .env
  echo "[+] .env generated"
  echo "    -> bootstrap admin password : ${ADMIN_PW}"
  echo "    -> grafana admin password   : ${GRAFANA_PW}"
fi

# ---- JWT keypair ----------------------------------------------------------
if [[ -f secrets/jwt_private.pem && $FORCE -eq 0 ]]; then
  echo "[=] JWT keypair exists"
else
  openssl genrsa -out secrets/jwt_private.pem 4096 2>/dev/null
  openssl rsa -in secrets/jwt_private.pem -pubout -out secrets/jwt_public.pem 2>/dev/null
  chmod 600 secrets/jwt_private.pem
  echo "[+] RSA JWT keypair generated (4096-bit)"
fi

# ---- TLS certificate ------------------------------------------------------
if [[ -f secrets/certs/satyameba.crt && $FORCE -eq 0 ]]; then
  echo "[=] TLS certificate exists"
else
  openssl req -x509 -newkey rsa:2048 -nodes \
    -keyout secrets/certs/satyameba.key \
    -out secrets/certs/satyameba.crt -days 825 \
    -subj "/CN=${DOMAIN}/O=SATYAMEBA/OU=Samaraho Mukherjee" \
    -addext "subjectAltName=DNS:${DOMAIN},DNS:localhost" 2>/dev/null
  chmod 600 secrets/certs/satyameba.key
  echo "[+] Self-signed TLS certificate generated for ${DOMAIN}"
  echo "    (replace with a real / Let's Encrypt cert for production)"
fi

echo "[✓] Secrets ready."
